version: 2.1

executors:
  node:
    working_directory: ~/microservices-demo
    docker:
      - image: circleci/node:10
        user: node

commands:
  setup_cli:
    description: Install the CLI and login
    parameters:
      api_host:
        type: string
        default: https://api.architect.io
      registry_host:
        type: string
        default: registry.architect.io
      app_host:
        type: string
        default: https://cloud.architect.io
    steps:
      - run:
          name: Setup NPM bin path
          command: |
            mkdir -p ~/.npm-global
            npm config set prefix '~/.npm-global'
            echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            echo $BASH_ENV
      - run:
          name: Install Architect CLI
          command: npm install -g @architect-io/cli
      - run:
          name: Configure environment
          command: |
            architect config:set api_host << parameters.api_host >>
            architect config:set app_host << parameters.app_host >>
            architect config:set registry_host << parameters.registry_host >>
      - run:
          name: Architect Login
          command: architect login -e $ARCHITECT_EMAIL -p $ARCHITECT_PASSWORD

jobs:
  prerelease:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - setup_cli
      - run:
          name: Push changed services to prod
          command: for dir in $(ls -d src/*); do architect push -s $dir -t latest; done
      - setup_cli:
          api_host: https://api.dev.architect.io
          app_host: https://cloud.dev.architect.io
          registry_host: registry.dev.architect.io
      - run:
          name: Push changed services to dev
          command: for dir in $(ls -d src/*); do architect push -s $dir -t latest; done

  release:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - setup_cli
      - run:
          name: Push changed services to prod
          command: for dir in $(ls -d src/*); do architect push -s $dir -t $CIRCLE_TAG; done
      - setup_cli:
          api_host: https://api.dev.architect.io
          app_host: https://cloud.dev.architect.io
          registry_host: registry.dev.architect.io
      - run:
          name: Push changed services to dev
          command: for dir in $(ls -d src/*); do architect push -s $dir -t $CIRCLE_TAG; done

workflows:
  version: 2
  prerelease-changed:
    jobs:
      - prerelease:
          filters:
            tags:
              ignore: /.*/
            branches:
              only:
                - master
  release-all:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
